
from gpiozero import LEDBoard
from gpiozero.tools import random_values
from signal import pause
import datetime 
import time

print 'Julians Weihnachtsbaum-App'

board24 = LEDBoard(4, pwm=True)
board23 = LEDBoard(5, pwm=True)
board22 = LEDBoard(6, pwm=True)
board21 = LEDBoard(7, pwm=True)
board20 = LEDBoard(8, pwm=True)
board19 = LEDBoard(9, pwm=True)
board18 = LEDBoard(10, pwm=True)
board17 = LEDBoard(11, pwm=True)
board16 = LEDBoard(12, pwm=True)
board15 = LEDBoard(13, pwm=True)
board14 = LEDBoard(14, pwm=True)
board13 = LEDBoard(15, pwm=True)
board12 = LEDBoard(16, pwm=True)
board11 = LEDBoard(17, pwm=True)
board10 = LEDBoard(18, pwm=True)
board09 = LEDBoard(19, pwm=True)
board08 = LEDBoard(20, pwm=True)
board07 = LEDBoard(21, pwm=True)
board06 = LEDBoard(22, pwm=True)
board05 = LEDBoard(23, pwm=True)
board04 = LEDBoard(24, pwm=True)
board03 = LEDBoard(25, pwm=True)
board02 = LEDBoard(26, pwm=True)
board01 = LEDBoard(27, pwm=True)

speed = 0.2

while True:
    
    now = datetime.datetime.now()
    day = now.strftime('%d')
    month = now.strftime('%m')
    anzahl = int(day)

    if month != '12':
        print 'Es ist NICHT Dezember. Julians Weihnachtsbaum leuchtet nur im Dezember'
        break
    if (anzahl >=24 ):
        board24.off()
        board23.off()
        board22.off()
        board21.off()
        board20.off()
        board19.off()
        board18.off()
        board17.off()
        board16.off()
        board15.off()
        board14.off()
        board13.off()
        board12.off()
        board11.off()
        board10.off()
        board09.off()
        board08.off()
        board07.off()
        board06.off()
        board05.off()
        board04.off()
        board03.off()
        board02.off()
        board01.off()
        time.sleep(speed)
        board24.on()
        board23.on()
        board22.on()
        board21.on()
        board20.on()
        board19.on()
        board18.on()
        board17.on()
        board16.on()
        board15.on()
        board14.on()
        board13.on()
        board12.on()
        board11.on()
        board10.on()
        board09.on()
        board08.on()
        board07.on()
        board06.on()
        board05.on()
        board04.on()
        board03.on()
        board02.on()
        board01.on()        
        time.sleep(speed)
    elif (anzahl == 23):
        board23.off()
        board22.off()
        board21.off()
        board20.off()
        board19.off()
        board18.off()
        board17.off()
        board16.off()
        board15.off()
        board14.off()
        board13.off()
        board12.off()
        board11.off()
        board10.off()
        board09.off()
        board08.off()
        board07.off()
        board06.off()
        board05.off()
        board04.off()
        board03.off()
        board02.off()
        board01.off()
        time.sleep(speed)
        board23.on()
        board22.on()
        board21.on()
        board20.on()
        board19.on()
        board18.on()
        board17.on()
        board16.on()
        board15.on()
        board14.on()
        board13.on()
        board12.on()
        board11.on()
        board10.on()
        board09.on()
        board08.on()
        board07.on()
        board06.on()
        board05.on()
        board04.on()
        board03.on()
        board02.on()
        board01.on()      
        time.sleep(speed)    
    elif (anzahl == 22):
        board22.off()
        board21.off()
        board20.off()
        board19.off()
        board18.off()
        board17.off()
        board16.off()
        board15.off()
        board14.off()
        board13.off()
        board12.off()
        board11.off()
        board10.off()
        board09.off()
        board08.off()
        board07.off()
        board06.off()
        board05.off()
        board04.off()
        board03.off()
        board02.off()
        board01.off()
        time.sleep(speed)
        board22.on()
        board21.on()
        board20.on()
        board19.on()
        board18.on()
        board17.on()
        board16.on()
        board15.on()
        board14.on()
        board13.on()
        board12.on()
        board11.on()
        board10.on()
        board09.on()
        board08.on()
        board07.on()
        board06.on()
        board05.on()
        board04.on()
        board03.on()
        board02.on()
        board01.on()      
        time.sleep(speed)    
    elif (anzahl == 21):
        board21.off()
        board20.off()
        board19.off()
        board18.off()
        board17.off()
        board16.off()
        board15.off()
        board14.off()
        board13.off()
        board12.off()
        board11.off()
        board10.off()
        board09.off()
        board08.off()
        board07.off()
        board06.off()
        board05.off()
        board04.off()
        board03.off()
        board02.off()
        board01.off()
        time.sleep(speed)
        board21.on()
        board20.on()
        board19.on()
        board18.on()
        board17.on()
        board16.on()
        board15.on()
        board14.on()
        board13.on()
        board12.on()
        board11.on()
        board10.on()
        board09.on()
        board08.on()
        board07.on()
        board06.on()
        board05.on()
        board04.on()
        board03.on()
        board02.on()
        board01.on()    
        time.sleep(speed)    
    elif (anzahl == 20):
        board20.off()
        board19.off()
        board18.off()
        board17.off()
        board16.off()
        board15.off()
        board14.off()
        board13.off()
        board12.off()
        board11.off()
        board10.off()
        board09.off()
        board08.off()
        board07.off()
        board06.off()
        board05.off()
        board04.off()
        board03.off()
        board02.off()
        board01.off()
        time.sleep(speed)
        board20.on()
        board19.on()
        board18.on()
        board17.on()
        board16.on()
        board15.on()
        board14.on()
        board13.on()
        board12.on()
        board11.on()
        board10.on()
        board09.on()
        board08.on()
        board07.on()
        board06.on()
        board05.on()
        board04.on()
        board03.on()
        board02.on()
        board01.on()   
        time.sleep(speed)    
    elif (anzahl == 19):
        board19.off()
        board18.off()
        board17.off()
        board16.off()
        board15.off()
        board14.off()
        board13.off()
        board12.off()
        board11.off()
        board10.off()
        board09.off()
        board08.off()
        board07.off()
        board06.off()
        board05.off()
        board04.off()
        board03.off()
        board02.off()
        board01.off()
        time.sleep(speed)
        board19.on()
        board18.on()
        board17.on()
        board16.on()
        board15.on()
        board14.on()
        board13.on()
        board12.on()
        board11.on()
        board10.on()
        board09.on()
        board08.on()
        board07.on()
        board06.on()
        board05.on()
        board04.on()
        board03.on()
        board02.on()
        board01.on()  
        time.sleep(speed)    
    elif (anzahl == 18):
        board18.off()
        board17.off()
        board16.off()
        board15.off()
        board14.off()
        board13.off()
        board12.off()
        board11.off()
        board10.off()
        board09.off()
        board08.off()
        board07.off()
        board06.off()
        board05.off()
        board04.off()
        board03.off()
        board02.off()
        board01.off()
        time.sleep(speed)
        board18.on()
        board17.on()
        board16.on()
        board15.on()
        board14.on()
        board13.on()
        board12.on()
        board11.on()
        board10.on()
        board09.on()
        board08.on()
        board07.on()
        board06.on()
        board05.on()
        board04.on()
        board03.on()
        board02.on()
        board01.on() 
        time.sleep(speed)    
    elif (anzahl == 17):
        board17.off()
        board16.off()
        board15.off()
        board14.off()
        board13.off()
        board12.off()
        board11.off()
        board10.off()
        board09.off()
        board08.off()
        board07.off()
        board06.off()
        board05.off()
        board04.off()
        board03.off()
        board02.off()
        board01.off()
        time.sleep(speed)
        board17.on()
        board16.on()
        board15.on()
        board14.on()
        board13.on()
        board12.on()
        board11.on()
        board10.on()
        board09.on()
        board08.on()
        board07.on()
        board06.on()
        board05.on()
        board04.on()
        board03.on()
        board02.on()
        board01.on() 
        time.sleep(speed)    
    elif (anzahl == 16):
        board16.off()
        board15.off()
        board14.off()
        board13.off()
        board12.off()
        board11.off()
        board10.off()
        board09.off()
        board08.off()
        time.sleep(speed * 3)
        board07.off()
        board06.off()
        board05.off()
        board04.off()
        board03.off()
        board02.off()
        board01.off()
        time.sleep(speed)
        board16.on()
        board15.on()
        board14.on()
        time.sleep(speed * 2)
        board13.on()
        board12.on()
        board11.on()
        board10.on()
        time.sleep(speed)
        board09.on()
        board08.on()
        board07.on()
        board06.on()
        time.sleep(speed)
        board05.on()
        board04.on()
        board03.on()
        time.sleep(speed)
        board02.on()
        board01.on()  
        time.sleep(speed)    
    elif (anzahl == 15):
        board15.off()
        board14.off()
        board13.off()
        board12.off()
        board11.off()
        board10.off()
        board09.off()
        board08.off()
        board07.off()
        board06.off()
        board05.off()
        board04.off()
        board03.off()
        board02.off()
        board01.off()
        time.sleep(speed)
        board15.on()
        board14.on()
        board13.on()
        board12.on()
        board11.on()
        board10.on()
        board09.on()
        board08.on()
        board07.on()
        board06.on()
        board05.on()
        board04.on()
        board03.on()
        board02.on()
        board01.on()   
        time.sleep(speed)    
    elif (anzahl == 14):
        board14.off()
        board13.off()
        board12.off()
        board11.off()
        board10.off()
        board09.off()
        board08.off()
        board07.off()
        board06.off()
        board05.off()
        board04.off()
        board03.off()
        board02.off()
        board01.off()
        time.sleep(speed)
        board14.on()
        board13.on()
        board12.on()
        board11.on()
        board10.on()
        board09.on()
        board08.on()
        board07.on()
        board06.on()
        board05.on()
        board04.on()
        board03.on()
        board02.on()
        board01.on()      
        time.sleep(speed)    
    elif (anzahl == 13):
        board13.off()
        board12.off()
        board11.off()
        board10.off()
        board09.off()
        board08.off()
        board07.off()
        board06.off()
        board05.off()
        board04.off()
        board03.off()
        board02.off()
        board01.off()
        time.sleep(speed)
        board13.on()
        board12.on()
        board11.on()
        board10.on()
        board09.on()
        board08.on()
        board07.on()
        board06.on()
        board05.on()
        board04.on()
        board03.on()
        board02.on()
        board01.on() 
        time.sleep(speed)    
    elif (anzahl == 12):
        board12.off()
        board11.off()
        board10.off()
        board09.off()
        board08.off()
        time.sleep(speed)
        board07.off()
        board06.off()
        time.sleep(speed)
        board05.off()
        board04.off()
        time.sleep(speed)
        board03.off()
        board02.off()
        board01.off()
        time.sleep(speed)
        board12.on()
        time.sleep(speed)
        board11.on()
        time.sleep(speed)
        board10.on()
        time.sleep(speed)
        board09.on()
        time.sleep(speed)
        board08.on()
        board07.on()
        board06.on()
        board05.on()
        time.sleep(speed)
        board04.on()
        board03.on()
        board02.on()
        time.sleep(speed * 3)
        board01.on()   
        time.sleep(speed)    
    elif (anzahl == 11):
        board11.off()
        board10.off()
        board09.off()
        board08.off()
        board07.off()
        board06.off()
        board05.off()
        board04.off()
        board03.off()
        board02.off()
        board01.off()
        time.sleep(speed)
        board11.on()
        board10.on()
        board09.on()
        board08.on()
        board07.on()
        board06.on()
        board05.on()
        board04.on()
        board03.on()
        board02.on()
        board01.on()    
        time.sleep(speed)    
    elif (anzahl == 10):
        board10.off()
        board09.off()
        board08.off()
        board07.off()
        board06.off()
        board05.off()
        board04.off()
        board03.off()
        board02.off()
        board01.off()
        time.sleep(speed)
        board10.on()
        board09.on()
        board08.on()
        board07.on()
        board06.on()
        board05.on()
        board04.on()
        board03.on()
        board02.on()
        board01.on()  
        time.sleep(speed)    
    elif (anzahl == 9):
        board09.off()
        board08.off()
        board07.off()
        board06.off()
        board05.off()
        board04.off()
        board03.off()
        board02.off()
        board01.off()
        time.sleep(speed)
        board09.on()
        board08.on()
        board07.on()
        board06.on()
        board05.on()
        board04.on()
        board03.on()
        board02.on()
        board01.on()   
        time.sleep(speed)    
    elif (anzahl == 8):
        board08.off()
        board07.off()
        board06.off()
        board05.off()
        board04.off()
        board03.off()
        board02.off()
        board01.off()
        time.sleep(speed)
        board08.on()
        board07.on()
        board06.on()
        board05.on()
        board04.on()
        board03.on()
        board02.on()
        board01.on()   
        time.sleep(speed)    
    elif (anzahl == 7):
        board07.off()
        board06.off()
        board05.off()
        board04.off()
        board03.off()
        board02.off()
        board01.off()
        time.sleep(speed)
        board07.on()
        board06.on()
        board05.on()
        board04.on()
        board03.on()
        board02.on()
        board01.on() 
        time.sleep(speed)    
    elif (anzahl == 6):
        board06.off()
        board05.off()
        board04.off()
        board03.off()
        board02.off()
        board01.off()
        time.sleep(speed)
        board06.on()
        board05.on()
        board04.on()
        board03.on()
        board02.on()
        board01.on()  
        time.sleep(speed)    
    elif (anzahl == 5):
        board05.off()
        board04.off()
        board03.off()
        board02.off()
        board01.off()
        time.sleep(speed)
        board05.on()
        board04.on()
        board03.on()
        board02.on()
        board01.on()    
        time.sleep(speed)    
    elif (anzahl == 4):
        board04.off()
        board03.off()
        board02.off()
        board01.off()
        time.sleep(speed)
        board04.on()
        board03.on()
        board02.on()
        board01.on()    
        time.sleep(speed)    
    elif (anzahl == 3):
        board03.off()
        board02.off()
        board01.off()
        time.sleep(speed)
        board03.on()
        board02.on()
        board01.on()    
        time.sleep(speed)  
    elif (anzahl == 2):
        board02.off()
        board01.off()
        time.sleep(speed)
        board02.on()
        board01.on()     
        time.sleep(speed)
    elif (anzahl == 1):
        board01.off()
        time.sleep(speed)
        board01.on()
        time.sleep(speed)

 
